// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 9u4jBEkqWUKrrXSfUUFFfk
// Component: dAAdljOIrTq
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { PlasmicHead } from "@plasmicapp/react-web"; // plasmic-import: 9R13-owMVa/codeComponent

import { useScreenVariants as useScreenVariantsgpwde9M3Mng } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: GPWDE9_m3Mng/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_feed_presell_ai.module.css"; // plasmic-import: 9u4jBEkqWUKrrXSfUUFFfk/projectcss
import sty from "./PlasmicBodyArticle1.module.css"; // plasmic-import: dAAdljOIrTq/css

export type PlasmicBodyArticle1__VariantMembers = {};
export type PlasmicBodyArticle1__VariantsArgs = {};
type VariantPropType = keyof PlasmicBodyArticle1__VariantsArgs;
export const PlasmicBodyArticle1__VariantProps = new Array<VariantPropType>();

export type PlasmicBodyArticle1__ArgsType = {};
type ArgPropType = keyof PlasmicBodyArticle1__ArgsType;
export const PlasmicBodyArticle1__ArgProps = new Array<ArgPropType>();

export type PlasmicBodyArticle1__OverridesType = {
  article1Body?: p.Flex<"div">;
  heroHeadline?: p.Flex<"div">;
  heroSubHeadline?: p.Flex<"div">;
  heroImage?: p.Flex<typeof p.PlasmicImg>;
  paragraph1?: p.Flex<"div">;
  image1?: p.Flex<typeof p.PlasmicImg>;
  paragraph2?: p.Flex<"div">;
  image2?: p.Flex<typeof p.PlasmicImg>;
  paragraph3?: p.Flex<"div">;
  image3?: p.Flex<typeof p.PlasmicImg>;
  paragraph4?: p.Flex<"div">;
  image4?: p.Flex<typeof p.PlasmicImg>;
  paragraph5?: p.Flex<"div">;
  image5?: p.Flex<typeof p.PlasmicImg>;
  paragraph6?: p.Flex<"div">;
  head?: p.Flex<typeof PlasmicHead>;
  image6?: p.Flex<typeof p.PlasmicImg>;
  paragraph7?: p.Flex<"div">;
  freeBox?: p.Flex<"div">;
  columns?: p.Flex<"div">;
  text?: p.Flex<"div">;
  image7?: p.Flex<typeof p.PlasmicImg>;
};

export interface DefaultBodyArticle1Props {
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicBodyArticle1__RenderFunc(props: {
  variants: PlasmicBodyArticle1__VariantsArgs;
  args: PlasmicBodyArticle1__ArgsType;
  overrides: PlasmicBodyArticle1__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsgpwde9M3Mng()
  });

  return (
    <div
      data-plasmic-name={"article1Body"}
      data-plasmic-override={overrides.article1Body}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.article1Body
      )}
    >
      <div
        data-plasmic-name={"heroHeadline"}
        data-plasmic-override={overrides.heroHeadline}
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.heroHeadline
        )}
      >
        {hasVariant(globalVariants, "screen", "mobileOnly") ? (
          <div
            className={projectcss.__wab_expr_html_text}
            dangerouslySetInnerHTML={{
              __html: (() => {
                try {
                 // return $ctx.fetchDyanamicData.records[0].fields.heroHeadline;

                  var ParaSbTexthead = $ctx.fetchDyanamicData.records[0].fields.heroHeadline;
                  var htmlhead = urlScheck(ParaSbTexthead); 
                 
                  function urlScheck(text) {
                    var regex = /\[([^\][]*)]/g;
                    var results = [], m;
                    while (m = regex.exec(text)) {
                    results.push(m[1]);         
                    }
                    const replaceDatahead = results;

                    var arrayLengthhead = replaceDatahead.length;
                    var  asas= 0;
                    for (var i=0; i <= arrayLengthhead; i++) {
                    
                     var urlRegSB = /(https?:\/\/[^\s]+)/g;
                     return text.replace(+ replaceDatahead + '').replace(urlRegSB, function (url) {
                     var laststringremovehead = url.replaceAll(")", "")
                     
                    
                    var onlyurlhead =  '<a href="' + laststringremovehead + '" style="color:#4896fa;text-decoration: underline #4896FA 1px;">' + replaceDatahead[asas] + '</a>';
                    asas ++ ;
                     
                    return onlyurlhead;
                    })
                  }
                  }
                 
                      const cleanedParagraphhead = htmlhead.replace(/\[(.*?.)\]/g, '');
                      const cleanedParagraphhead2  = cleanedParagraphhead.replace('(', '<span>').replace('(', '</span>');
                      const cleanedParagraphhead1  = cleanedParagraphhead2.replace('(', '<span>').replace('(', '</span>');

                      const regex = /\*\*(.*?)\*\*/g; // define the regular expression pattern
                      const boldedTexthead = cleanedParagraphhead1.replace(regex, '<b>$1</b>');
                                    // undersore replace with italic
                      const Italichead = boldedTexthead.replace(/_([^_]+)_/g, "<i>$1</i>");
                                    // ~~ replace with strikethrough
                      const strikethroughead = Italichead.replace(/~~([^~]+)~~/g, "<s style='text-decoration: line-through;'>$1</s>");
                                  // `` replace with code
                      const code21head = strikethroughead.replace(/`([^`]+)`/g, "<code style='background-color: #F1F1F1;padding: 2px;'>$1</code>");
                      return code21head;

                } catch (e) {
                  if (e instanceof TypeError) {
                    return "Enter some text";
                  }
                  throw e;
                }
              })()
            }}
          />
        ) : (
          <div
            className={projectcss.__wab_expr_html_text}
            dangerouslySetInnerHTML={{
              __html: (() => {
                try {
                 // return $ctx.fetchDyanamicData.records[0].fields.heroHeadline;
                 var ParaSbTexthead = $ctx.fetchDyanamicData.records[0].fields.heroHeadline;
                 var htmlhead = urlScheck(ParaSbTexthead); 
                
                 function urlScheck(text) {
                   var regex = /\[([^\][]*)]/g;
                   var results = [], m;
                   while (m = regex.exec(text)) {
                   results.push(m[1]);         
                   }
                   const replaceDatahead = results;

                   var arrayLengthhead = replaceDatahead.length;
                   var  asas= 0;
                   for (var i=0; i <= arrayLengthhead; i++) {
                   
                    var urlRegSB = /(https?:\/\/[^\s]+)/g;
                    return text.replace(+ replaceDatahead + '').replace(urlRegSB, function (url) {
                    var laststringremovehead = url.replaceAll(")", "")
                    
                   
                   var onlyurlhead =  '<a href="' + laststringremovehead + '" style="color:#4896fa;text-decoration: underline #4896FA 1px;">' + replaceDatahead[asas] + '</a>';
                   asas ++ ;
                    
                   return onlyurlhead;
                   })
                 }
                 }
                
                     const cleanedParagraphhead = htmlhead.replace(/\[(.*?.)\]/g, '');
                     const cleanedParagraphhead2  = cleanedParagraphhead.replace('(', '<span>').replace('(', '</span>');
                     const cleanedParagraphhead1  = cleanedParagraphhead2.replace('(', '<span>').replace('(', '</span>');

                     const regex = /\*\*(.*?)\*\*/g; // define the regular expression pattern
                     const boldedTexthead = cleanedParagraphhead1.replace(regex, '<b>$1</b>');
                                   // undersore replace with italic
                     const Italichead = boldedTexthead.replace(/_([^_]+)_/g, "<i>$1</i>");
                                   // ~~ replace with strikethrough
                     const strikethroughead = Italichead.replace(/~~([^~]+)~~/g, "<s style='text-decoration: line-through;'>$1</s>");
                                 // `` replace with code
                     const code21head = strikethroughead.replace(/`([^`]+)`/g, "<code style='background-color: #F1F1F1;padding: 2px;'>$1</code>");
                     return code21head;

                } catch (e) {
                  if (e instanceof TypeError) {
                    return "Enter some text";
                  }
                  throw e;
                }
              })()
            }}
          />
        )}
      </div>

      <div
        data-plasmic-name={"heroSubHeadline"}
        data-plasmic-override={overrides.heroSubHeadline}
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.heroSubHeadline
        )}
      >
        {hasVariant(globalVariants, "screen", "mobileOnly") ? (
          <div
            className={projectcss.__wab_expr_html_text}
            dangerouslySetInnerHTML={{
              __html: (() => {
                try {
                 // return $ctx.fetchDyanamicData.records[0].fields
                  //  .heroSubHeadline;
                  var ParaSbText = $ctx.fetchDyanamicData.records[0].fields.heroSubHeadline;
                  var html = urlScheck(ParaSbText); 
                 
                  function urlScheck(text) {
                    var regex = /\[([^\][]*)]/g;
                    var results = [], m;
                    while (m = regex.exec(text)) {
                    results.push(m[1]);         
                    }
                    const replaceData = results;

                    var arrayLength = replaceData.length;
                    var  asas= 0;
                    for (var i=0; i <= arrayLength; i++) {
                    
                     var urlRegSB = /(https?:\/\/[^\s]+)/g;
                     return text.replace(+ replaceData + '').replace(urlRegSB, function (url) {
                     var laststringremove = url.replaceAll(")", "")
                     
                    
                    var onlyurl =  '<a href="' + laststringremove + '" style="color:#4896fa;text-decoration: underline #4896FA 1px;">' + replaceData[asas] + '</a>';
                    asas ++ ;
                     
                    return onlyurl;
                    })
                  }
                  }
                 
                      const cleanedParagraph = html.replace(/\[(.*?.)\]/g, '');
                      const cleanedParagraph21  = cleanedParagraph.replace('(', '<span>').replace('(', '</span>');
                      const cleanedParagraphhh  = cleanedParagraph21.replace('(', '<span>').replace('(', '</span>');

                      const regex = /\*\*(.*?)\*\*/g; // define the regular expression pattern
                      const boldedText = cleanedParagraphhh.replace(regex, '<b>$1</b>');
                                    // undersore replace with italic
                      const Italic = boldedText.replace(/_([^_]+)_/g, "<i>$1</i>");
                                    // ~~ replace with strikethrough
                      const strikethrough = Italic.replace(/~~([^~]+)~~/g, "<s style='text-decoration: line-through;'>$1</s>");
                                  // `` replace with code
                      const code21 = strikethrough.replace(/`([^`]+)`/g, "<code style='background-color: #F1F1F1;padding: 2px;'>$1</code>");
                      return code21;

                } catch (e) {
                  if (e instanceof TypeError) {
                    return "Enter some text";
                  }
                  throw e;
                }
              })()
            }}
          />
        ) : (
          <div
            className={projectcss.__wab_expr_html_text}
            dangerouslySetInnerHTML={{
              __html: (() => {
                try {
                 // return $ctx.fetchDyanamicData.records[0].fields
                   // .heroSubHeadline;
                    var ParaSbText = $ctx.fetchDyanamicData.records[0].fields.heroSubHeadline;
                    var html = urlScheck(ParaSbText); 
                   
                    function urlScheck(text) {
                      var regex = /\[([^\][]*)]/g;
                      var results = [], m;
                      while (m = regex.exec(text)) {
                      results.push(m[1]);         
                      }
                      const replaceData = results;
                     
                      var arrayLength = replaceData.length;
                      var  asas= 0;
                      for (var i=0; i <= arrayLength; i++) {
                      
                       var urlRegSB = /(https?:\/\/[^\s]+)/g;
                       return text.replace(+ replaceData + '').replace(urlRegSB, function (url) {
                       var laststringremove = url.replaceAll(")", "")
                      
                      
                      var onlyurl =  '<a href="' + laststringremove + '" style="color:#4896fa;text-decoration: underline #4896FA 1px;">' + replaceData[asas] + '</a>';
                      asas ++ ;
                       
                      return onlyurl;
                      })
                    }
                    }
                   
                        const cleanedParagraph = html.replace(/\[(.*?.)\]/g, '');
                        const cleanedParagraph21  = cleanedParagraph.replace('(', '<span>').replace('(', '</span>');
                        const cleanedParagraphhh  = cleanedParagraph21.replace('(', '<span>').replace('(', '</span>');
                      
                        const regex = /\*\*(.*?)\*\*/g; // define the regular expression pattern
                        const boldedText = cleanedParagraphhh.replace(regex, '<b>$1</b>');
                                      // undersore replace with italic
                        const Italic = boldedText.replace(/_([^_]+)_/g, "<i>$1</i>");
                                      // ~~ replace with strikethrough
                        const strikethrough = Italic.replace(/~~([^~]+)~~/g, "<s style='text-decoration: line-through;'>$1</s>");
                                    // `` replace with code
                        const code21 = strikethrough.replace(/`([^`]+)`/g, "<code style='background-color: #F1F1F1;padding: 2px;'>$1</code>");
                        return code21;
  
                } catch (e) {
                  if (e instanceof TypeError) {
                    return "Enter some text";
                  }
                  throw e;
                }
              })()
            }}
          />
        )}
      </div>

      <p.PlasmicLink
        className={classNames(projectcss.all, projectcss.a, sty.link___5AFGq)}
        component={Link}
        href={(() => {
          try {
            return $ctx.fetchDyanamicData.records[0].fields["Step 2 URL"];
          } catch (e) {
            if (e instanceof TypeError) {
              return undefined;
            }
            throw e;
          }
        })()}
        platform={"nextjs"}
      >
        <p.PlasmicImg
          data-plasmic-name={"heroImage"}
          data-plasmic-override={overrides.heroImage}
          alt={""}
          className={classNames(sty.heroImage)}
          displayHeight={
            hasVariant(globalVariants, "screen", "mobileOnly")
              ? ("auto" as const)
              : ("auto" as const)
          }
          displayMaxHeight={
            hasVariant(globalVariants, "screen", "mobileOnly")
              ? ("400px" as const)
              : ("400px" as const)
          }
          displayMaxWidth={
            hasVariant(globalVariants, "screen", "mobileOnly")
              ? ("100%" as const)
              : ("100%" as const)
          }
          displayMinHeight={"0" as const}
          displayMinWidth={"0" as const}
          displayWidth={
            hasVariant(globalVariants, "screen", "mobileOnly")
              ? ("354px" as const)
              : ("750px" as const)
          }
          loading={"lazy" as const}
          src={
            hasVariant(globalVariants, "screen", "mobileOnly")
              ? (() => {
                  try {
                    return $ctx.fetchDyanamicData.records[0].fields.heroImage[0]
                      .url;
                  } catch (e) {
                    if (e instanceof TypeError) {
                      return undefined;
                    }
                    throw e;
                  }
                })()
              : (() => {
                  try {
                    return $ctx.fetchDyanamicData.records[0].fields.heroImage[0]
                      .url;
                  } catch (e) {
                    if (e instanceof TypeError) {
                      return undefined;
                    }
                    throw e;
                  }
                })()
          }
        />
      </p.PlasmicLink>

      <div
        data-plasmic-name={"paragraph1"}
        data-plasmic-override={overrides.paragraph1}
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.paragraph1
        )}
      >
        {hasVariant(globalVariants, "screen", "mobileOnly")
          ? (
            <div
              className={projectcss.__wab_expr_html_text}
              dangerouslySetInnerHTML={{
                __html: (() => {
              try {
               // return $ctx.fetchDyanamicData.records[0].fields.paragraph1;
               var ParaSbTextPara1 = $ctx.fetchDyanamicData.records[0].fields.paragraph1;
               var htmlPara1 = urlScheck(ParaSbTextPara1); 
             
               function urlScheck(text) {
                 var regexPara1 = /\[([^\][]*)]/g;
                 var results = [], m;
                 while (m = regexPara1.exec(text)) {
                 results.push(m[1]);         
                 }
                 const replaceDataPara1 = results;
                 
                 var arrayLengthPara1 = replaceDataPara1.length;
                 
                 var  asas= 0;
                 for (var i=0; i <= arrayLengthPara1; i++) {
                 
                  var urlRegSBPara1 = /(https?:\/\/[^\s]+)/g;
                  return text.replace(+ replaceDataPara1 + '').replace(urlRegSBPara1, function (url) {
                  var laststringremovePara1 = url.replaceAll(")", "")
                 
                 
                 var onlyurlPara1 =  '<a href="' + laststringremovePara1 + '" style="color:#4896fa;text-decoration: underline #4896FA 1px;">' + replaceDataPara1[asas] + '</a>';
                
                 asas ++ ;
                  
                 return onlyurlPara1;
                 })
               }
               }
              
                   const cleanedParagraphPara1 = htmlPara1.replace(/\[(.*?.)\]/g, '');
                   const cleanedParagraph21Para1  = cleanedParagraphPara1.replace('(', '<span>').replace('(', '</span>');
                   const cleanedParagraphhhPara1Para1  = cleanedParagraph21Para1.replace('(', '<span>').replace('(', '</span>');

                   const regexPara121 = /\*\*(.*?)\*\*/g; // define the regular expression pattern
                   const boldedTextPara1 = cleanedParagraphhhPara1Para1.replace(regexPara121, '<b>$1</b>');
                                 // undersore replace with italic
                   const ItalicPara1 = boldedTextPara1.replace(/_([^_]+)_/g, "<i>$1</i>");
                                 // ~~ replace with strikethrough
                   const strikethroughPara1 = ItalicPara1.replace(/~~([^~]+)~~/g, "<s style='text-decoration: line-through;'>$1</s>");
                               // `` replace with code
                   const code21Para1 = strikethroughPara1.replace(/`([^`]+)`/g, "<code style='background-color: #F1F1F1;padding: 2px;'>$1</code>");
                   return code21Para1;


              } catch (e) {
                if (e instanceof TypeError) {
                  return "Enter some text";
                }
                throw e;
              }
            })()
          }}
        />
      ) : (
            <div
              className={projectcss.__wab_expr_html_text}
              dangerouslySetInnerHTML={{
                __html: (() => {
              try {
              //  return $ctx.fetchDyanamicData.records[0].fields.paragraph1;
           
                  var ParaSbTextPara1 = $ctx.fetchDyanamicData.records[0].fields.paragraph1;
                  var htmlPara1 = urlScheck(ParaSbTextPara1); 
                
                  function urlScheck(text) {
                    var regexPara1 = /\[([^\][]*)]/g;
                    var results = [], m;
                    while (m = regexPara1.exec(text)) {
                    results.push(m[1]);         
                    }
                    const replaceDataPara1 = results;
                    
                    var arrayLengthPara1 = replaceDataPara1.length;
                    
                    var  asas= 0;
                    for (var i=0; i <= arrayLengthPara1; i++) {
                    
                     var urlRegSBPara1 = /(https?:\/\/[^\s]+)/g;
                     return text.replace(+ replaceDataPara1 + '').replace(urlRegSBPara1, function (url) {
                     var laststringremovePara1 = url.replaceAll(")", "")
                    
                    
                    var onlyurlPara1 =  '<a href="' + laststringremovePara1 + '" style="color:#4896fa;text-decoration: underline #4896FA 1px;">' + replaceDataPara1[asas] + '</a>';
                   
                    asas ++ ;
                     
                    return onlyurlPara1;
                    })
                  }
                  }
                 
                      const cleanedParagraphPara1 = htmlPara1.replace(/\[(.*?.)\]/g, '');

                      const cleanedParagraph21Para1  = cleanedParagraphPara1.replace('(', '<span>').replace('(', '</span>');
                      const cleanedParagraphhhPara1Para1  = cleanedParagraph21Para1.replace('(', '<span>').replace('(', '</span>');
                      const regexPara121 = /\*\*(.*?)\*\*/g; // define the regular expression pattern
                      const boldedTextPara1 = cleanedParagraphhhPara1Para1.replace(regexPara121, '<b>$1</b>');
                                    // undersore replace with italic
                      const ItalicPara1 = boldedTextPara1.replace(/_([^_]+)_/g, "<i>$1</i>");
                                    // ~~ replace with strikethrough
                      const strikethroughPara1 = ItalicPara1.replace(/~~([^~]+)~~/g, "<s style='text-decoration: line-through;'>$1</s>");
                                  // `` replace with code
                      const code21Para1 = strikethroughPara1.replace(/`([^`]+)`/g, "<code style='background-color: #F1F1F1;padding: 2px;'>$1</code>");
                      return code21Para1;


              } catch (e) {
                if (e instanceof TypeError) {
                  return "Enter some text";
                }
                throw e;
              }
            })()
          }}
        />
      )}
    </div>

      <p.PlasmicLink
        className={classNames(projectcss.all, projectcss.a, sty.link__xbqJg)}
        component={Link}
        href={(() => {
          try {
            return $ctx.fetchDyanamicData.records[0].fields["Step 2 URL"];
          } catch (e) {
            if (e instanceof TypeError) {
              return undefined;
            }
            throw e;
          }
        })()}
        platform={"nextjs"}
      >
        <p.PlasmicImg
          data-plasmic-name={"image1"}
          data-plasmic-override={overrides.image1}
          alt={""}
          className={classNames(sty.image1)}
          displayHeight={
            hasVariant(globalVariants, "screen", "mobileOnly")
              ? ("auto" as const)
              : ("auto" as const)
          }
          displayMaxHeight={
            hasVariant(globalVariants, "screen", "mobileOnly")
              ? ("400px" as const)
              : ("400px" as const)
          }
          displayMaxWidth={
            hasVariant(globalVariants, "screen", "mobileOnly")
              ? ("100%" as const)
              : ("100%" as const)
          }
          displayMinHeight={"0" as const}
          displayMinWidth={"0" as const}
          displayWidth={
            hasVariant(globalVariants, "screen", "mobileOnly")
              ? ("354px" as const)
              : ("750px" as const)
          }
          loading={"lazy" as const}
          src={
            hasVariant(globalVariants, "screen", "mobileOnly")
              ? (() => {
                  try {
                    return $ctx.fetchDyanamicData.records[0].fields.image1[0]
                      .url;
                  } catch (e) {
                    if (e instanceof TypeError) {
                      return undefined;
                    }
                    throw e;
                  }
                })()
              : (() => {
                  try {
                    return $ctx.fetchDyanamicData.records[0].fields.image1[0]
                      .url;
                  } catch (e) {
                    if (e instanceof TypeError) {
                      return undefined;
                    }
                    throw e;
                  }
                })()
          }
        />
      </p.PlasmicLink>

      <div
        data-plasmic-name={"paragraph2"}
        data-plasmic-override={overrides.paragraph2}
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.paragraph2
        )}
      >
        {hasVariant(globalVariants, "screen", "mobileOnly")
         ? (
          <div
            className={projectcss.__wab_expr_html_text}
            dangerouslySetInnerHTML={{
              __html: (() => {
              try {
               // return $ctx.fetchDyanamicData.records[0].fields.paragraph2;
               var ParaSbTextPara2 = $ctx.fetchDyanamicData.records[0].fields.paragraph2;
               var htmlPara2 = urlScheck(ParaSbTextPara2); 
 
               function urlScheck(text) {
                 var regexPara2 = /\[([^\][]*)]/g;
                 var results = [], m;
                 while (m = regexPara2.exec(text)) {
                 results.push(m[1]);         
                 }
                 const replaceDataPara2 = results;
                 
                 var arrayLengthPara2 = replaceDataPara2.length;
                 
                 var  asas= 0;
                 for (var i=0; i <= arrayLengthPara2; i++) {
                 
                  var urlRegSBPara2 = /(https?:\/\/[^\s]+)/g;
                  return text.replace(+ replaceDataPara2 + '').replace(urlRegSBPara2, function (url) {
                  var laststringremovePara2 = url.replaceAll(")", "")

                 
                 var onlyurlPara2 =  '<a href="' + laststringremovePara2 + '" style="color:#4896fa;text-decoration: underline #4896FA 1px;">' + replaceDataPara2[asas] + '</a>';
                 asas ++ ;
                 return onlyurlPara2;
                 })
               }
               }
              
                   const cleanedParagraphPara2 = htmlPara2.replace(/\[(.*?.)\]/g, '');

                   const cleanedParagraph21Para2  = cleanedParagraphPara2.replace('(', '<span>').replace('(', '</span>');
                   const cleanedParagraphhhPara1Para2  = cleanedParagraph21Para2.replace('(', '<span>').replace('(', '</span>');
                   const regexPara121 = /\*\*(.*?)\*\*/g; // define the regular expression pattern
                   const boldedTextPara2 = cleanedParagraphhhPara1Para2.replace(regexPara121, '<b>$1</b>');
                                 // undersore replace with italic
                   const ItalicPara2 = boldedTextPara2.replace(/_([^_]+)_/g, "<i>$1</i>");
                                 // ~~ replace with strikethrough
                   const strikethroughPara2 = ItalicPara2.replace(/~~([^~]+)~~/g, "<s style='text-decoration: line-through;'>$1</s>");
                               // `` replace with code
                   const code21Para2 = strikethroughPara2.replace(/`([^`]+)`/g, "<code style='background-color: #F1F1F1;padding: 2px;'>$1</code>");
                   return code21Para2;


              } catch (e) {
                if (e instanceof TypeError) {
                  return "Enter some text";
                }
                throw e;
              }
            })()
          }}
        />
      ) : (
            <div
              className={projectcss.__wab_expr_html_text}
              dangerouslySetInnerHTML={{
                __html: (() => {
              try {
               // return $ctx.fetchDyanamicData.records[0].fields.paragraph2;
               var ParaSbTextPara2 = $ctx.fetchDyanamicData.records[0].fields.paragraph2;
               var htmlPara2 = urlScheck(ParaSbTextPara2); 
             
               function urlScheck(text) {
                 var regexPara1 = /\[([^\][]*)]/g;
                 var results = [], m;
                 while (m = regexPara1.exec(text)) {
                 results.push(m[1]);         
                 }
                 const replaceDataPara2 = results;
                 
                 var arrayLengthPara2 = replaceDataPara2.length;
                 
                 var  asas= 0;
                 for (var i=0; i <= arrayLengthPara2; i++) {
                 
                 var urlRegSBPara1 = /(https?:\/\/[^\s]+)/g;
                 return text.replace(+ replaceDataPara2 + '').replace(urlRegSBPara1, function (url) {
                 var laststringremovePara2 = url.replaceAll(")", "")
                               
                 var onlyurlPara2 =  '<a href="' + laststringremovePara2 + '" style="color:#4896fa;text-decoration: underline #4896FA 1px;">' + replaceDataPara2[asas] + '</a>';
                
                 asas ++ ;
                  
                 return onlyurlPara2;
                 })
               }
               }
                   const cleanedParagraphPara2 = htmlPara2.replace(/\[(.*?.)\]/g, '');

                   const cleanedParagraph21Para2  = cleanedParagraphPara2.replace('(', '<span>').replace('(', '</span>');
                   const cleanedParagraphhhPara1Para1  = cleanedParagraph21Para2.replace('(', '<span>').replace('(', '</span>');
                   const regexPara121 = /\*\*(.*?)\*\*/g; // define the regular expression pattern
                   const boldedTextPara2 = cleanedParagraphhhPara1Para1.replace(regexPara121, '<b>$1</b>');
                  // console.log(boldedTextPara2);

                                 // undersore replace with italic
                   const ItalicPara2 = boldedTextPara2.replace(/_([^_]+)_/g, "<i>$1</i>");
                                 // ~~ replace with strikethrough
                   const strikethroughPara2 = ItalicPara2.replace(/~~([^~]+)~~/g, "<s style='text-decoration: line-through;'>$1</s>");
                               // `` replace with code
                   const code21Para2 = strikethroughPara2.replace(/`([^`]+)`/g, "<code style='background-color: #F1F1F1;padding: 2px;'>$1</code>");
                   return code21Para2;

              } catch (e) {
                if (e instanceof TypeError) {
                  return "Enter some text";
                }
                throw e;
              }
            })()
          }}
        />
      )}
    </div>
      <p.PlasmicLink
        className={classNames(projectcss.all, projectcss.a, sty.link__emysg)}
        component={Link}
        href={(() => {
          try {
            return $ctx.fetchDyanamicData.records[0].fields["Step 2 URL"];
          } catch (e) {
            if (e instanceof TypeError) {
              return undefined;
            }
            throw e;
          }
        })()}
        platform={"nextjs"}
      >
        <p.PlasmicImg
          data-plasmic-name={"image2"}
          data-plasmic-override={overrides.image2}
          alt={""}
          className={classNames(sty.image2)}
          displayHeight={
            hasVariant(globalVariants, "screen", "mobileOnly")
              ? ("auto" as const)
              : ("auto" as const)
          }
          displayMaxHeight={
            hasVariant(globalVariants, "screen", "mobileOnly")
              ? ("300px" as const)
              : ("400px" as const)
          }
          displayMaxWidth={
            hasVariant(globalVariants, "screen", "mobileOnly")
              ? ("100%" as const)
              : ("100%" as const)
          }
          displayMinHeight={"0" as const}
          displayMinWidth={"0" as const}
          displayWidth={
            hasVariant(globalVariants, "screen", "mobileOnly")
              ? ("354px" as const)
              : ("750px" as const)
          }
          loading={"lazy" as const}
          src={(() => {
            try {
              return $ctx.fetchDyanamicData.records[0].fields.image2[0].url;
            } catch (e) {
              if (e instanceof TypeError) {
                return undefined;
              }
              throw e;
            }
          })()}
        />
      </p.PlasmicLink>

      <div
        data-plasmic-name={"paragraph3"}
        data-plasmic-override={overrides.paragraph3}
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.paragraph3
        )}
      >
     
            <div
              className={projectcss.__wab_expr_html_text}
              dangerouslySetInnerHTML={{
                __html: (() => {
          try {
           // return $ctx.fetchDyanamicData.records[0].fields.paragraph3;
 
           var ParaSbTextPara3 = $ctx.fetchDyanamicData.records[0].fields.paragraph3;
               var htmlPara3 = urlScheck(ParaSbTextPara3); 
             
               function urlScheck(text) {
                 var regexPara3 = /\[([^\][]*)]/g;
                 var results = [], m;
                 while (m = regexPara3.exec(text)) {
                 results.push(m[1]);         
                 }
                 const replaceDataPara3 = results;
                 
                 var arrayLengthPara3 = replaceDataPara3.length;
                 
                 var  asas= 0;
                 for (var i=0; i <= arrayLengthPara3; i++) {
                 
                 var urlRegSBPara3 = /(https?:\/\/[^\s]+)/g;
                 return text.replace(+ replaceDataPara3 + '').replace(urlRegSBPara3, function (url) {
                 var laststringremovePara3 = url.replaceAll(")", "")
                 
                 var onlyurlPara3 =  '<a href="' + laststringremovePara3 + '" style="color:#4896fa;text-decoration: underline #4896FA 1px;">' + replaceDataPara3[asas] + '</a>';               
                 asas ++ ;
                  
                 return onlyurlPara3;
                 })
               }
               }
                   const cleanedParagraphPara3 = htmlPara3.replace(/\[(.*?.)\]/g, '');

                   const cleanedParagraph21Para3  = cleanedParagraphPara3.replace('(', '<span>').replace('(', '</span>');
                   const cleanedParagraphhhPara1Para3  = cleanedParagraph21Para3.replace('(', '<span>').replace('(', '</span>');
                   const regexPara121 = /\*\*(.*?)\*\*/g; // define the regular expression pattern
                   const boldedTextPara3 = cleanedParagraphhhPara1Para3.replace(regexPara121, '<b>$1</b>');
                                 // undersore replace with italic
                   const ItalicPara3 = boldedTextPara3.replace(/_([^_]+)_/g, "<i>$1</i>");
                                 // ~~ replace with strikethrough
                   const strikethroughPara3 = ItalicPara3.replace(/~~([^~]+)~~/g, "<s style='text-decoration: line-through;'>$1</s>");
                               // `` replace with code
                   const code21Para3 = strikethroughPara3.replace(/`([^`]+)`/g, "<code style='background-color: #F1F1F1;padding: 2px;'>$1</code>");
                   return code21Para3;

          } catch (e) {
            if (e instanceof TypeError) {
              return "Enter some text";
            }
            throw e;
          }
        })()
      }}
    />
      </div>

      <p.PlasmicLink
        className={classNames(projectcss.all, projectcss.a, sty.link__u4Ht)}
        component={Link}
        href={(() => {
          try {
            return $ctx.fetchDyanamicData.records[0].fields["Step 2 URL"];
          } catch (e) {
            if (e instanceof TypeError) {
              return undefined;
            }
            throw e;
          }
        })()}
        platform={"nextjs"}
      >
        <p.PlasmicImg
          data-plasmic-name={"image3"}
          data-plasmic-override={overrides.image3}
          alt={""}
          className={classNames(sty.image3)}
          displayHeight={
            hasVariant(globalVariants, "screen", "mobileOnly")
              ? ("auto" as const)
              : ("auto" as const)
          }
          displayMaxHeight={
            hasVariant(globalVariants, "screen", "mobileOnly")
              ? ("400px" as const)
              : ("400px" as const)
          }
          displayMaxWidth={
            hasVariant(globalVariants, "screen", "mobileOnly")
              ? ("100%" as const)
              : ("100%" as const)
          }
          displayMinHeight={"0" as const}
          displayMinWidth={"0" as const}
          displayWidth={
            hasVariant(globalVariants, "screen", "mobileOnly")
              ? ("354px" as const)
              : ("750px" as const)
          }
          loading={"lazy" as const}
          src={(() => {
            try {
              return $ctx.fetchDyanamicData.records[0].fields.image3[0].url;
            } catch (e) {
              if (e instanceof TypeError) {
                return undefined;
              }
              throw e;
            }
          })()}
        />
      </p.PlasmicLink>

      <div
        data-plasmic-name={"paragraph4"}
        data-plasmic-override={overrides.paragraph4}
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.paragraph4
        )}
      >
         <div
              className={projectcss.__wab_expr_html_text}
              dangerouslySetInnerHTML={{
                __html: (() => {
          try {
           // return $ctx.fetchDyanamicData.records[0].fields.paragraph4;
           var ParaSbTextPara4 = $ctx.fetchDyanamicData.records[0].fields.paragraph4;
           var htmlPara4 = urlScheck(ParaSbTextPara4); 
         
           function urlScheck(text) {
             var regexPara4 = /\[([^\][]*)]/g;
             var results = [], m;
             while (m = regexPara4.exec(text)) {
             results.push(m[1]);         
             }
             const replaceDataPara4 = results;
             
             var arrayLengthPara4 = replaceDataPara4.length;
             
             var  asas= 0;
             for (var i=0; i <= arrayLengthPara4; i++) {
             
              var urlRegSBPara4 = /(https?:\/\/[^\s]+)/g;
              return text.replace(+ replaceDataPara4 + '').replace(urlRegSBPara4, function (url) {
              var laststringremovePara4 = url.replaceAll(")", "")
             
             
             var onlyurlPara4 =  '<a href="' + laststringremovePara4 + '" style="color:#4896fa;text-decoration: underline #4896FA 1px;">' + replaceDataPara4[asas] + '</a>';
            
             asas ++ ;
              
             return onlyurlPara4;
             })
           }
           }
               const cleanedParagraphPara4 = htmlPara4.replace(/\[(.*?.)\]/g, '');

               const cleanedParagraph21Para4  = cleanedParagraphPara4.replace('(', '<span>').replace('(', '</span>');
               const cleanedParagraphhhPara1Para4  = cleanedParagraph21Para4.replace('(', '<span>').replace('(', '</span>');
               const regexPara1214 = /\*\*(.*?)\*\*/g; // define the regular expression pattern
               const boldedTextPara4 = cleanedParagraphhhPara1Para4.replace(regexPara1214, '<b>$1</b>');
               //console.log(boldedTextPara4);
                             // undersore replace with italic
               const ItalicPara4 = boldedTextPara4.replace(/_([^_]+)_/g, "<i>$1</i>");
                             // ~~ replace with strikethrough
               const strikethroughPara4 = ItalicPara4.replace(/~~([^~]+)~~/g, "<s style='text-decoration: line-through;'>$1</s>");
                           // `` replace with code
               const code21Para4 = strikethroughPara4.replace(/`([^`]+)`/g, "<code style='background-color: #F1F1F1;padding: 2px;'>$1</code>");
               return code21Para4;


          } catch (e) {
            if (e instanceof TypeError) {
              return "Enter some text";
            }
            throw e;
          }
        })()
      }}
    />
      </div>

      <p.PlasmicLink
        className={classNames(projectcss.all, projectcss.a, sty.link__f1Cp)}
        component={Link}
        href={(() => {
          try {
            return $ctx.fetchDyanamicData.records[0].fields["Step 2 URL"];
          } catch (e) {
            if (e instanceof TypeError) {
              return undefined;
            }
            throw e;
          }
        })()}
        platform={"nextjs"}
      >
        <p.PlasmicImg
          data-plasmic-name={"image4"}
          data-plasmic-override={overrides.image4}
          alt={""}
          className={classNames(sty.image4)}
          displayHeight={
            hasVariant(globalVariants, "screen", "mobileOnly")
              ? ("auto" as const)
              : ("auto" as const)
          }
          displayMaxHeight={
            hasVariant(globalVariants, "screen", "mobileOnly")
              ? ("400px" as const)
              : ("400px" as const)
          }
          displayMaxWidth={
            hasVariant(globalVariants, "screen", "mobileOnly")
              ? ("100%" as const)
              : ("100%" as const)
          }
          displayMinHeight={"0" as const}
          displayMinWidth={"0" as const}
          displayWidth={
            hasVariant(globalVariants, "screen", "mobileOnly")
              ? ("354px" as const)
              : ("750px" as const)
          }
          loading={"lazy" as const}
          src={(() => {
            try {
              return $ctx.fetchDyanamicData.records[0].fields.image4[0].url;
            } catch (e) {
              if (e instanceof TypeError) {
                return undefined;
              }
              throw e;
            }
          })()}
        />
      </p.PlasmicLink>

      <div
        data-plasmic-name={"paragraph5"}
        data-plasmic-override={overrides.paragraph5}
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.paragraph5
        )}
      >
        <div
              className={projectcss.__wab_expr_html_text}
              dangerouslySetInnerHTML={{
                __html: (() => {
          try {
           // return $ctx.fetchDyanamicData.records[0].fields.paragraph4;
           var ParaSbTextPara5 = $ctx.fetchDyanamicData.records[0].fields.paragraph5;
           var htmlPara5 = urlScheck(ParaSbTextPara5); 
         
           function urlScheck(text) {
             var regexPara5 = /\[([^\][]*)]/g;
             var results = [], m;
             while (m = regexPara5.exec(text)) {
             results.push(m[1]);         
             }
             const replaceDataPara5 = results;
             
             var arrayLengthPara5 = replaceDataPara5.length;
             
             var  asas= 0;
             for (var i=0; i <= arrayLengthPara5; i++) {
             
              var urlRegSBPara5 = /(https?:\/\/[^\s]+)/g;
              return text.replace(+ replaceDataPara5 + '').replace(urlRegSBPara5, function (url) {
              var laststringremovePara5 = url.replaceAll(")", "")
             
             
             var onlyurlPara5 =  '<a href="' + laststringremovePara5 + '" style="color:#4896fa;text-decoration: underline #4896FA 1px;">' + replaceDataPara5[asas] + '</a>';           
             asas ++ ;
              
             return onlyurlPara5;
             })
           }
           }
               const cleanedParagraphPara5 = htmlPara5.replace(/\[(.*?.)\]/g, '');

               const cleanedParagraph21Para5  = cleanedParagraphPara5.replace('(', '<span>').replace('(', '</span>');
               const cleanedParagraphhhPara1Para5  = cleanedParagraph21Para5.replace('(', '<span>').replace('(', '</span>');
               const regexPara1214 = /\*\*(.*?)\*\*/g; // define the regular expression pattern
               const boldedTextPara5 = cleanedParagraphhhPara1Para5.replace(regexPara1214, '<b>$1</b>');
               //console.log(boldedTextPara5);
                             // undersore replace with italic
               const ItalicPara5 = boldedTextPara5.replace(/_([^_]+)_/g, "<i>$1</i>");
                             // ~~ replace with strikethrough
               const strikethroughPara5 = ItalicPara5.replace(/~~([^~]+)~~/g, "<s style='text-decoration: line-through;'>$1</s>");
                           // `` replace with code
               const code21Para5 = strikethroughPara5.replace(/`([^`]+)`/g, "<code style='background-color: #F1F1F1;padding: 2px;'>$1</code>");
               return code21Para5;


          } catch (e) {
            if (e instanceof TypeError) {
              return "Enter some text";
            }
            throw e;
          }
        })()
      }}
    />
      </div>

      <p.PlasmicLink
        className={classNames(projectcss.all, projectcss.a, sty.link__vCbxa)}
        component={Link}
        href={(() => {
          try {
            return $ctx.fetchDyanamicData.records[0].fields["Step 2 URL"];
          } catch (e) {
            if (e instanceof TypeError) {
              return undefined;
            }
            throw e;
          }
        })()}
        platform={"nextjs"}
      >
        <p.PlasmicImg
          data-plasmic-name={"image5"}
          data-plasmic-override={overrides.image5}
          alt={""}
          className={classNames(sty.image5)}
          displayHeight={
            hasVariant(globalVariants, "screen", "mobileOnly")
              ? ("auto" as const)
              : ("auto" as const)
          }
          displayMaxHeight={
            hasVariant(globalVariants, "screen", "mobileOnly")
              ? ("400px" as const)
              : ("400px" as const)
          }
          displayMaxWidth={
            hasVariant(globalVariants, "screen", "mobileOnly")
              ? ("100%" as const)
              : ("100%" as const)
          }
          displayMinHeight={"0" as const}
          displayMinWidth={"0" as const}
          displayWidth={
            hasVariant(globalVariants, "screen", "mobileOnly")
              ? ("354px" as const)
              : ("750px" as const)
          }
          loading={"lazy" as const}
          src={(() => {
            try {
              return $ctx.fetchDyanamicData.records[0].fields.image5[0].url;
            } catch (e) {
              if (e instanceof TypeError) {
                return undefined;
              }
              throw e;
            }
          })()}
        />
      </p.PlasmicLink>

      <div
        data-plasmic-name={"paragraph6"}
        data-plasmic-override={overrides.paragraph6}
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.paragraph6
        )}
      >
         <div
              className={projectcss.__wab_expr_html_text}
              dangerouslySetInnerHTML={{
                __html: (() => {
          try {
           // return $ctx.fetchDyanamicData.records[0].fields.paragraph4;
           var ParaSbTextPara6 = $ctx.fetchDyanamicData.records[0].fields.paragraph6;
           var htmlPara6 = urlScheck(ParaSbTextPara6); 
         
           function urlScheck(text) {
             var regexPara6 = /\[([^\][]*)]/g;
             var results = [], m;
             while (m = regexPara6.exec(text)) {
             results.push(m[1]);         
             }
             const replaceDataPara6 = results;
             
             var arrayLengthPara6 = replaceDataPara6.length;
             
             var  asas= 0;
             for (var i=0; i <= arrayLengthPara6; i++) {
             
              var urlRegSBPara6 = /(https?:\/\/[^\s]+)/g;
              return text.replace(+ replaceDataPara6 + '').replace(urlRegSBPara6, function (url) {
              var laststringremovePara6 = url.replaceAll(")", "")
             
             
             var onlyurlPara6 =  '<a href="' + laststringremovePara6 + '" style="color:#4896fa;text-decoration: underline #4896FA 1px;">' + replaceDataPara6[asas] + '</a>';           
             asas ++ ;
              
             return onlyurlPara6;
             })
           }
           }
               const cleanedParagraphPara6 = htmlPara6.replace(/\[(.*?.)\]/g, '');

               const cleanedParagraph21Para6  = cleanedParagraphPara6.replace('(', '<span>').replace('(', '</span>');
               const cleanedParagraphhhPara1Para6  = cleanedParagraph21Para6.replace('(', '<span>').replace('(', '</span>');
               const regexPara1214 = /\*\*(.*?)\*\*/g; // define the regular expression pattern
               const boldedTextPara6 = cleanedParagraphhhPara1Para6.replace(regexPara1214, '<b>$1</b>');
                             // undersore replace with italic
               const ItalicPara6 = boldedTextPara6.replace(/_([^_]+)_/g, "<i>$1</i>");
                             // ~~ replace with strikethrough
               const strikethroughPara6 = ItalicPara6.replace(/~~([^~]+)~~/g, "<s style='text-decoration: line-through;'>$1</s>");
                           // `` replace with code
               const code21Para6 = strikethroughPara6.replace(/`([^`]+)`/g, "<code style='background-color: #F1F1F1;padding: 2px;'>$1</code>");
               return code21Para6;


          } catch (e) {
            if (e instanceof TypeError) {
              return "Enter some text";
            }
            throw e;
          }
        })()
      }}
    />
      </div>

      <PlasmicHead
        data-plasmic-name={"head"}
        data-plasmic-override={overrides.head}
        className={classNames("__wab_instance", sty.head)}
      />

      <p.PlasmicLink
        className={classNames(projectcss.all, projectcss.a, sty.link__qu78B)}
        component={Link}
        href={(() => {
          try {
            return $ctx.fetchDyanamicData.records[0].fields["Step 2 URL"];
          } catch (e) {
            if (e instanceof TypeError) {
              return undefined;
            }
            throw e;
          }
        })()}
        platform={"nextjs"}
      >
        <p.PlasmicImg
          data-plasmic-name={"image6"}
          data-plasmic-override={overrides.image6}
          alt={""}
          className={classNames(sty.image6)}
          displayHeight={
            hasVariant(globalVariants, "screen", "mobileOnly")
              ? ("auto" as const)
              : ("auto" as const)
          }
          displayMaxHeight={
            hasVariant(globalVariants, "screen", "mobileOnly")
              ? ("400px" as const)
              : ("400px" as const)
          }
          displayMaxWidth={
            hasVariant(globalVariants, "screen", "mobileOnly")
              ? ("100%" as const)
              : ("100%" as const)
          }
          displayMinHeight={"0" as const}
          displayMinWidth={"0" as const}
          displayWidth={
            hasVariant(globalVariants, "screen", "mobileOnly")
              ? ("354px" as const)
              : ("750px" as const)
          }
          loading={"lazy" as const}
          src={(() => {
            try {
              return $ctx.fetchDyanamicData.records[0].fields.image6[0].url;
            } catch (e) {
              if (e instanceof TypeError) {
                return undefined;
              }
              throw e;
            }
          })()}
        />
      </p.PlasmicLink>

      <div
        data-plasmic-name={"paragraph7"}
        data-plasmic-override={overrides.paragraph7}
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.paragraph7
        )}
      >
       <div
              className={projectcss.__wab_expr_html_text}
              dangerouslySetInnerHTML={{
                __html: (() => {
          try {
           // return $ctx.fetchDyanamicData.records[0].fields.paragraph4;
           var ParaSbTextPara7 = $ctx.fetchDyanamicData.records[0].fields.paragraph7;
           var htmlPara7 = urlScheck(ParaSbTextPara7); 
         
           function urlScheck(text) {
             var regexPara7 = /\[([^\][]*)]/g;
             var results = [], m;
             while (m = regexPara7.exec(text)) {
             results.push(m[1]);         
             }
             const replaceDataPara7 = results;
             
             var arrayLengthPara7 = replaceDataPara7.length;
             
             var  asas= 0;
             for (var i=0; i <= arrayLengthPara7; i++) {
             
              var urlRegSBPara7 = /(https?:\/\/[^\s]+)/g;
              return text.replace(+ replaceDataPara7 + '').replace(urlRegSBPara7, function (url) {
              var laststringremovePara7 = url.replaceAll(")", "")
                         
             var onlyurlPara7 =  '<a href="' + laststringremovePara7 + '" style="color:#4896fa;text-decoration: underline #4896FA 1px;">' + replaceDataPara7[asas] + '</a>';           
             asas ++ ;
              
             return onlyurlPara7;
             })
           }
           }
               const cleanedParagraphPara7 = htmlPara7.replace(/\[(.*?.)\]/g, '');

               const cleanedParagraph21Para7  = cleanedParagraphPara7.replace('(', '<span>').replace('(', '</span>');
               const cleanedParagraphhhPara1Para7  = cleanedParagraph21Para7.replace('(', '<span>').replace('(', '</span>');
               const regexPara1214 = /\*\*(.*?)\*\*/g; // define the regular expression pattern
               const boldedTextPara7 = cleanedParagraphhhPara1Para7.replace(regexPara1214, '<b>$1</b>');
                             // undersore replace with italic
               const ItalicPara7 = boldedTextPara7.replace(/_([^_]+)_/g, "<i>$1</i>");
                             // ~~ replace with strikethrough
               const strikethroughPara7 = ItalicPara7.replace(/~~([^~]+)~~/g, "<s style='text-decoration: line-through;'>$1</s>");
                           // `` replace with code
               const code21Para7 = strikethroughPara7.replace(/`([^`]+)`/g, "<code style='background-color: #F1F1F1;padding: 2px;'>$1</code>");
               return code21Para7;

          } catch (e) {
            if (e instanceof TypeError) {
              return "Enter some text";
            }
            throw e;
          }
        })()
      }}
    />
      </div>

      {(hasVariant(globalVariants, "screen", "mobileOnly") ? true : true) ? (
        <div
          data-plasmic-name={"freeBox"}
          data-plasmic-override={overrides.freeBox}
          className={classNames(projectcss.all, sty.freeBox)}
        >
          <div
            data-plasmic-name={"columns"}
            data-plasmic-override={overrides.columns}
            className={classNames(projectcss.all, sty.columns)}
          >
            <div className={classNames(projectcss.all, sty.column___1OYu)}>
              <p.PlasmicLink
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.link__wfrHy
                )}
                component={Link}
                href={(() => {
                  try {
                    return $ctx.fetchDyanamicData.records[0].fields[
                      "Step 2 URL"
                    ];
                  } catch (e) {
                    if (e instanceof TypeError) {
                      return undefined;
                    }
                    throw e;
                  }
                })()}
                platform={"nextjs"}
              >
                {(() => {
                  try {
                    return $ctx.fetchDyanamicData.records[0].fields.aCTA;
                  } catch (e) {
                    if (e instanceof TypeError) {
                      return "CLAIM FREE PODS";
                    }
                    throw e;
                  }
                })()}
              </p.PlasmicLink>
            </div>

            <div className={classNames(projectcss.all, sty.column__mgnSw)}>
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__x5KNk)}
                displayHeight={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? ("70%" as const)
                    : ("80%" as const)
                }
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? ("8px" as const)
                    : ("8px" as const)
                }
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/feed_presell_ai/images/_4F0Afe7D15505Bfe240E785E7Ac88B6Cwebp.webp",
                  fullWidth: 3,
                  fullHeight: 90,
                  aspectRatio: undefined
                }}
              />
            </div>

            <div className={classNames(projectcss.all, sty.column__rInz)}>
              <div
                data-plasmic-name={"text"}
                data-plasmic-override={overrides.text}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text
                )}
              >
                {(() => {
                  try {
                    return $ctx.fetchDyanamicData.records[0].fields.aOutroH3;
                  } catch (e) {
                    if (e instanceof TypeError) {
                      return "Enter some text";
                    }
                    throw e;
                  }
                })()}
              </div>

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img___9AHk6)}
                displayHeight={"auto" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"auto" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/feed_presell_ai/images/starpng.png",
                  fullWidth: 142,
                  fullHeight: 21,
                  aspectRatio: undefined
                }}
              />
            </div>
          </div>
        </div>
      ) : null}

      <p.PlasmicLink
        className={classNames(projectcss.all, projectcss.a, sty.link___4XSyy)}
        component={Link}
        href={(() => {
          try {
            return $ctx.fetchDyanamicData.records[0].fields["Step 2 URL"];
          } catch (e) {
            if (e instanceof TypeError) {
              return undefined;
            }
            throw e;
          }
        })()}
        platform={"nextjs"}
      >
        <p.PlasmicImg
          data-plasmic-name={"image7"}
          data-plasmic-override={overrides.image7}
          alt={""}
          className={classNames(sty.image7)}
          displayHeight={
            hasVariant(globalVariants, "screen", "mobileOnly")
              ? ("auto" as const)
              : ("auto" as const)
          }
          displayMaxHeight={"400px" as const}
          displayMaxWidth={
            hasVariant(globalVariants, "screen", "mobileOnly")
              ? ("100%" as const)
              : ("100%" as const)
          }
          displayMinHeight={"0" as const}
          displayMinWidth={"0" as const}
          displayWidth={
            hasVariant(globalVariants, "screen", "mobileOnly")
              ? ("354px" as const)
              : ("750px" as const)
          }
          loading={"lazy" as const}
          src={(() => {
            try {
              return $ctx.fetchDyanamicData.records[0].fields.image7[0].url;
            } catch (e) {
              if (e instanceof TypeError) {
                return undefined;
              }
              throw e;
            }
          })()}
        />
      </p.PlasmicLink>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  article1Body: [
    "article1Body",
    "heroHeadline",
    "heroSubHeadline",
    "heroImage",
    "paragraph1",
    "image1",
    "paragraph2",
    "image2",
    "paragraph3",
    "image3",
    "paragraph4",
    "image4",
    "paragraph5",
    "image5",
    "paragraph6",
    "head",
    "image6",
    "paragraph7",
    "freeBox",
    "columns",
    "text",
    "image7"
  ],
  heroHeadline: ["heroHeadline"],
  heroSubHeadline: ["heroSubHeadline"],
  heroImage: ["heroImage"],
  paragraph1: ["paragraph1"],
  image1: ["image1"],
  paragraph2: ["paragraph2"],
  image2: ["image2"],
  paragraph3: ["paragraph3"],
  image3: ["image3"],
  paragraph4: ["paragraph4"],
  image4: ["image4"],
  paragraph5: ["paragraph5"],
  image5: ["image5"],
  paragraph6: ["paragraph6"],
  head: ["head"],
  image6: ["image6"],
  paragraph7: ["paragraph7"],
  freeBox: ["freeBox", "columns", "text"],
  columns: ["columns", "text"],
  text: ["text"],
  image7: ["image7"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  article1Body: "div";
  heroHeadline: "div";
  heroSubHeadline: "div";
  heroImage: typeof p.PlasmicImg;
  paragraph1: "div";
  image1: typeof p.PlasmicImg;
  paragraph2: "div";
  image2: typeof p.PlasmicImg;
  paragraph3: "div";
  image3: typeof p.PlasmicImg;
  paragraph4: "div";
  image4: typeof p.PlasmicImg;
  paragraph5: "div";
  image5: typeof p.PlasmicImg;
  paragraph6: "div";
  head: typeof PlasmicHead;
  image6: typeof p.PlasmicImg;
  paragraph7: "div";
  freeBox: "div";
  columns: "div";
  text: "div";
  image7: typeof p.PlasmicImg;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicBodyArticle1__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicBodyArticle1__VariantsArgs;
    args?: PlasmicBodyArticle1__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicBodyArticle1__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicBodyArticle1__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicBodyArticle1__ArgProps,
          internalVariantPropNames: PlasmicBodyArticle1__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicBodyArticle1__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "article1Body") {
    func.displayName = "PlasmicBodyArticle1";
  } else {
    func.displayName = `PlasmicBodyArticle1.${nodeName}`;
  }
  return func;
}

export const PlasmicBodyArticle1 = Object.assign(
  // Top-level PlasmicBodyArticle1 renders the root element
  makeNodeComponent("article1Body"),
  {
    // Helper components rendering sub-elements
    heroHeadline: makeNodeComponent("heroHeadline"),
    heroSubHeadline: makeNodeComponent("heroSubHeadline"),
    heroImage: makeNodeComponent("heroImage"),
    paragraph1: makeNodeComponent("paragraph1"),
    image1: makeNodeComponent("image1"),
    paragraph2: makeNodeComponent("paragraph2"),
    image2: makeNodeComponent("image2"),
    paragraph3: makeNodeComponent("paragraph3"),
    image3: makeNodeComponent("image3"),
    paragraph4: makeNodeComponent("paragraph4"),
    image4: makeNodeComponent("image4"),
    paragraph5: makeNodeComponent("paragraph5"),
    image5: makeNodeComponent("image5"),
    paragraph6: makeNodeComponent("paragraph6"),
    head: makeNodeComponent("head"),
    image6: makeNodeComponent("image6"),
    paragraph7: makeNodeComponent("paragraph7"),
    freeBox: makeNodeComponent("freeBox"),
    columns: makeNodeComponent("columns"),
    text: makeNodeComponent("text"),
    image7: makeNodeComponent("image7"),

    // Metadata about props expected for PlasmicBodyArticle1
    internalVariantProps: PlasmicBodyArticle1__VariantProps,
    internalArgProps: PlasmicBodyArticle1__ArgProps
  }
);

export default PlasmicBodyArticle1;
/* prettier-ignore-end */
